---
- name: RedHat - Install tmux package if it isn't installed 
  package:
    name: "tmux"

- name: RedHat - copy tmux config to home directory
  template:
    src:  tmux.conf.j2
    dest: /home/{{item.UserName}}/.tmux.conf
    owner:  "{{item.UserName}}"
    group:  "{{item.PrimaryGroup| default('users')}}"
    backup: no
    mode: 0644
  with_items: "{{TmuxInfo}}"

- name: RedHat - copy tmux startup to home directory for work
  template:
    src:  tmux.startup.work.j2
    dest: /home/{{item.UserName}}/.tmux.startup
    owner:  "{{item.UserName}}"
    group:  "{{item.PrimaryGroup| default('users')}}"
    backup: no
    mode: 0755
  with_items: "{{TmuxInfo}}"
  when: 
    - item.UserName == "jxpsys"

- name: RedHat - copy tmux startup to home directory for home
  template:
    src:  tmux.startup.home.j2
    dest: /home/{{item.UserName}}/.tmux.startup
    owner:  "{{item.UserName}}"
    group:  "{{item.PrimaryGroup| default('users')}}"
    backup: no
    mode: 0755
  with_items: "{{TmuxInfo}}"
  when: 
    - item.UserName != "jxpsys"
